CREATE TABLE IF NOT EXISTS experiment_run (
 id VARCHAR(64) PRIMARY KEY, process_id VARCHAR(64), outcome VARCHAR(32) NOT NULL,
 reason VARCHAR(2000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS device_command (
 id VARCHAR(64) PRIMARY KEY, run_id VARCHAR(64) NOT NULL, execution_id VARCHAR(64) NOT NULL,
 node_id VARCHAR(128) NOT NULL, device_id VARCHAR(128) NOT NULL, action VARCHAR(128) NOT NULL,
 status VARCHAR(32) NOT NULL, result_json CLOB, error VARCHAR(2000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS device_lease (id INT PRIMARY KEY, run_id VARCHAR(64));
MERGE INTO device_lease (id) KEY(id) SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM device_lease WHERE id=1);
