import { Phase, type PhaseConfig } from "@/types";

export const PHASES: Record<Phase, PhaseConfig> = {
  [Phase.IDLE]: {
    id: Phase.IDLE,
    label: "Event Standby",
    labelZh: "等待事件",
    description: "等待 GXLF 生命周期事件流。",
    camera: "overview",
  },
  [Phase.PARAM_DISPATCH]: {
    id: Phase.PARAM_DISPATCH,
    label: "Parameter Dispatch",
    labelZh: "参数下发",
    description: "总控向系统/接口下发发次参数，服务实例返回接收与状态迁移事件。",
    camera: "overview",
  },
  [Phase.PARALLEL_STARTUP]: {
    id: Phase.PARALLEL_STARTUP,
    label: "Parallel Startup",
    labelZh: "并行启动",
    description: "前端光源、预放、同步、靶瞄、测量取样和控制环境等系统并行进入准备链路。",
    camera: "overview",
  },
  [Phase.CLEARANCE_LOCKDOWN]: {
    id: Phase.CLEARANCE_LOCKDOWN,
    label: "Clearance & Lockdown",
    labelZh: "清场与锁门",
    description: "控制环境、人员计数和屏蔽门事件驱动安全边界状态变化。",
    camera: "overview",
  },
  [Phase.ENERGY_ALIGNMENT]: {
    id: Phase.ENERGY_ALIGNMENT,
    label: "Energy Loop & Alignment",
    labelZh: "能量闭环与光路准直",
    description: "预放闭环、多程光路准直、靶瞄定位和光束引导进入打靶准备状态。",
    camera: "beamPath",
  },
  [Phase.READINESS_CHECK]: {
    id: Phase.READINESS_CHECK,
    label: "Readiness Check",
    labelZh: "准备状态检查",
    description: "事件流中的准备完成节点汇合为当前发次的 readiness 状态。",
    camera: "overview",
  },
  [Phase.FINAL_PREP]: {
    id: Phase.FINAL_PREP,
    label: "Final Preparation",
    labelZh: "正式发射准备",
    description: "诊断、频率转换、泵浦、预放、测量和开关驱动进入正式发射前置链路。",
    camera: "overview",
  },
  [Phase.CHARGING]: {
    id: Phase.CHARGING,
    label: "Shot Charging",
    labelZh: "发射充电",
    description: "泵浦和开关驱动相关事件驱动充电、警灯和安全状态变化。",
    camera: "capacitorBank",
  },
  [Phase.COUNTDOWN]: {
    id: Phase.COUNTDOWN,
    label: "Sync Countdown",
    labelZh: "同步触发倒计时",
    description: "同步触发事件启动 T+0/T+3/T+5 倒计时语义。",
    camera: "targetChamber",
  },
  [Phase.FIRING]: {
    id: Phase.FIRING,
    label: "Firing",
    labelZh: "正式触发",
    description: "泵浦、开关驱动、频率转换和束线事件共同驱动发射视觉。",
    camera: "targetChamber",
  },
  [Phase.TARGET_IMPLOSION]: {
    id: Phase.TARGET_IMPLOSION,
    label: "Target Implosion",
    labelZh: "靶丸爆缩",
    description: "正式发射完成事件触发靶室中心瞬态发光和诊断采集。",
    camera: "targetChamber",
  },
  [Phase.DATA_COLLECTION]: {
    id: Phase.DATA_COLLECTION,
    label: "Data Collection",
    labelZh: "数据采集",
    description: "诊断、测量、种子源、预放、泵浦和开关驱动事件进入采集链路。",
    camera: "overview",
  },
  [Phase.POST_PROCESS]: {
    id: Phase.POST_PROCESS,
    label: "Post-Processing",
    labelZh: "后处理",
    description: "后处理、待机、吹扫、收靶和开门等事件驱动设施回退。",
    camera: "overview",
  },
  [Phase.COMPLETE]: {
    id: Phase.COMPLETE,
    label: "Complete",
    labelZh: "流程结束",
    description: "事件流结束或发射任务完成。",
    camera: "cinematic",
  },
};
